# Generated by Django 5.1.4 on 2024-12-30 12:49

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vehicles', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Offense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_infringement', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=4)),
                ('points', models.IntegerField()),
                ('penalty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(blank=True, max_length=10, unique=True)),
                ('fine_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('issue_date', models.DateTimeField(auto_now_add=True)),
                ('due_date', models.DateTimeField(default=datetime.datetime(2025, 1, 13, 12, 49, 3, 949158, tzinfo=datetime.timezone.utc))),
                ('is_paid', models.BooleanField(default=False)),
                ('motorist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_received', to=settings.AUTH_USER_MODEL)),
                ('offence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='tickets.offense')),
                ('official', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets_issued', to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='vehicles.vehicle')),
            ],
        ),
    ]
