# Generated by Django 5.1.4 on 2024-12-30 13:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Offense',
            new_name='Offence',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 13, 17, 12, 230338, tzinfo=datetime.timezone.utc)),
        ),
    ]
