# Generated by Django 5.1.4 on 2024-12-30 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_offense_offence_alter_ticket_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 13, 23, 59, 985302, tzinfo=datetime.timezone.utc)),
        ),
    ]
