# Generated by Django 5.1.4 on 2024-12-30 14:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticket_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='fine_amount',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 14, 41, 37, 196604, tzinfo=datetime.timezone.utc)),
        ),
    ]
