# Generated by Django 5.1.4 on 2024-12-30 14:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_remove_ticket_fine_amount_alter_ticket_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 14, 44, 2, 30924, tzinfo=datetime.timezone.utc)),
        ),
    ]
