# Generated by Django 5.1.4 on 2024-12-30 14:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 13, 14, 45, 10, 849984, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_no',
            field=models.CharField(blank=True, max_length=1000, unique=True),
        ),
    ]
